### ISSUE TITLE
Consul azure installation

### ISSUE THREAD

**Issue by crixo** [wwwlicious/servicestack-discovery-consul#15]
The plugin documentation says "A consul agent must be running on the same machine as the AppHost.". How does it apply using azure web app(that's the ss  AppHost).
Is there any sample/guide to configure the consul plugin for azure deploy?

**Comment by wwwlicious** [comment]
Hi @crixo, sorry for the delayed response as I was away last week. 

We don't currently have any guides for setting this up in Azure as it is not something we have tried/needed yet. I'm not familiar with how web apps run in Azure either to know quite how it could be setup with Consul. 

The reason to run consul on the same apphost is that it eliminates issues with network reliability by running over a local loopback address, something which also aids the performance of service lookups.

I'll take a look at this scenario more closely this week to see what is possible but if you have any suggestions based on your own experiences with Azure, please let me know.
