### ISSUE TITLE
Support for Service Stack v5

### ISSUE THREAD

**Issue by DavidFBakker** [wwwlicious/servicestack-discovery-consul#23]
Are there any plans to port to v5 of Service Stack?

**Comment by wwwlicious** [comment]
@DavidFBakker Yes, I will look at updating the package in the next few weeks.

**Comment by DavidFBakker** [comment]
Great thank you. can you make it a .net standard 2 library??

**Comment by wwwlicious** [comment]
Well .net standard certainly, maybe 1.6 and net 4.x something to avoid breaking existing users or forcing upgrades.

**Comment by tmdoit-zz** [comment]
Any progress?

**Comment by chris-sung** [comment]
@wwwlicious any progress?

**Comment by wwwlicious** [comment]
released 5.0.1 to nuget
